/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba.pkg2;

import javax.swing.JSlider;

/**
 *
 * @author porti
 */
public class REPRODUCTOR extends javax.swing.JFrame {

    /**
     * Creates new form REPRODUCTOR
     */
    public REPRODUCTOR() {
        initComponents();
        sliderVolumen = new JSlider(JSlider.VERTICAL, 0, 100, 25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        AñadirCancionALista = new javax.swing.JButton();
        CarpetaMusica = new javax.swing.JButton();
        sliderVolumen = new javax.swing.JSlider();
        Barra_DuracionCancion = new javax.swing.JSlider();
        IconoMusica = new javax.swing.JButton();
        Btn_PlayCancion = new javax.swing.JButton();
        Btn_Adelantar = new javax.swing.JButton();
        Btn_Atrasar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreDeLaCancion = new javax.swing.JTextField();
        NombreDeArtista = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), java.awt.Color.white));
        jToolBar1.setRollover(true);

        AñadirCancionALista.setBackground(new java.awt.Color(255, 255, 255));
        AñadirCancionALista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/pkg2/add.png"))); // NOI18N
        AñadirCancionALista.setFocusable(false);
        AñadirCancionALista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AñadirCancionALista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AñadirCancionALista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirCancionAListaActionPerformed(evt);
            }
        });
        jToolBar1.add(AñadirCancionALista);

        CarpetaMusica.setBackground(new java.awt.Color(255, 255, 255));
        CarpetaMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/pkg2/carpeta musica.png"))); // NOI18N
        CarpetaMusica.setFocusable(false);
        CarpetaMusica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CarpetaMusica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CarpetaMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarpetaMusicaActionPerformed(evt);
            }
        });
        jToolBar1.add(CarpetaMusica);

        sliderVolumen.setBackground(new java.awt.Color(255, 255, 255));
        sliderVolumen.setForeground(new java.awt.Color(0, 0, 153));
        sliderVolumen.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderVolumen.setValue(20);
        sliderVolumen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sliderVolumen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderVolumen.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sliderVolumenAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Barra_DuracionCancion.setBackground(new java.awt.Color(255, 255, 255));
        Barra_DuracionCancion.setForeground(new java.awt.Color(0, 102, 51));
        Barra_DuracionCancion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Barra_DuracionCancion.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Barra_DuracionCancionAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        IconoMusica.setText("cancion");

        Btn_PlayCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/pkg2/play.png"))); // NOI18N
        Btn_PlayCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PlayCancionActionPerformed(evt);
            }
        });

        Btn_Adelantar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/pkg2/adelantar2.png"))); // NOI18N
        Btn_Adelantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AdelantarActionPerformed(evt);
            }
        });

        Btn_Atrasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/pkg2/atrasar.png"))); // NOI18N
        Btn_Atrasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AtrasarActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/pkg2/volumen.png"))); // NOI18N

        jLabel1.setText("Nombre de la Cancion:");

        jLabel2.setText("Nombre del artista:");

        NombreDeLaCancion.setEditable(false);
        NombreDeLaCancion.setBackground(new java.awt.Color(255, 255, 255));
        NombreDeLaCancion.setBorder(null);

        NombreDeArtista.setEditable(false);
        NombreDeArtista.setBackground(new java.awt.Color(255, 255, 255));
        NombreDeArtista.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(Btn_Atrasar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_PlayCancion)
                .addGap(111, 111, 111)
                .addComponent(Btn_Adelantar)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Barra_DuracionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IconoMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NombreDeLaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NombreDeArtista)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderVolumen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(sliderVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(NombreDeLaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(NombreDeArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IconoMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addComponent(Barra_DuracionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_PlayCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Adelantar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Atrasar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderVolumenAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sliderVolumenAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_sliderVolumenAncestorAdded

    private void Btn_AdelantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AdelantarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_AdelantarActionPerformed

    private void AñadirCancionAListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirCancionAListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirCancionAListaActionPerformed

    private void CarpetaMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarpetaMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarpetaMusicaActionPerformed

    private void Barra_DuracionCancionAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Barra_DuracionCancionAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Barra_DuracionCancionAncestorAdded

    private void Btn_PlayCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PlayCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_PlayCancionActionPerformed

    private void Btn_AtrasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AtrasarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_AtrasarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REPRODUCTOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REPRODUCTOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REPRODUCTOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REPRODUCTOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REPRODUCTOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirCancionALista;
    private javax.swing.JSlider Barra_DuracionCancion;
    private javax.swing.JButton Btn_Adelantar;
    private javax.swing.JButton Btn_Atrasar;
    private javax.swing.JButton Btn_PlayCancion;
    private javax.swing.JButton CarpetaMusica;
    private javax.swing.JButton IconoMusica;
    private javax.swing.JTextField NombreDeArtista;
    private javax.swing.JTextField NombreDeLaCancion;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JSlider sliderVolumen;
    // End of variables declaration//GEN-END:variables
}
